[package]
name = "rust"
version = "0.1.0"
authors = ["jorgen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "0.9"
rand = "0.8.3"
ansi_term = "0.12.1"